export const doctors = [
    {
      name: "Dr. Sarah Johnson",
      appointmentTime: "9:00 AM - 12:00 PM",
      fees: 150,
      category: "Cardiologist",
      hospital: "City Heart Hospital",
      gender: "Female",
      id: 1,
    },
    {
      name: "Dr. Robert Smith",
      appointmentTime: "2:00 PM - 6:00 PM",
      fees: 200,
      category: "Dermatologist",
      hospital: "Skin Care Clinic",
      gender: "Male",
      id: 2,
    },
    {
      name: "Dr. Emily Davis",
      appointmentTime: "10:00 AM - 1:00 PM",
      fees: 180,
      category: "Pediatrician",
      hospital: "Children's Medical Center",
      gender: "Female",
      id: 3,
    },
    {
      name: "Dr. Michael Brown",
      appointmentTime: "11:00 AM - 3:00 PM",
      fees: 250,
      category: "Orthopedic Surgeon",
      hospital: "Prime Ortho Hospital",
      gender: "Male",
      id: 4,
    },
    {
      name: "Dr. Lisa Thompson",
      appointmentTime: "3:00 PM - 7:00 PM",
      fees: 220,
      category: "Psychiatrist",
      hospital: "Mind Wellness Center",
      gender: "Female",
      id: 5,
    },
    {
      name: "Dr. Daniel Wilson",
      appointmentTime: "8:00 AM - 12:00 PM",
      fees: 300,
      category: "Oncologist",
      hospital: "Cancer Care Hospital",
      gender: "Male",
      id: 6,
    },
    {
      name: "Dr. Olivia Martinez",
      appointmentTime: "1:00 PM - 4:00 PM",
      fees: 170,
      category: "Allergist/Immunologist",
      hospital: "Allergy Relief Center",
      gender: "Female",
      id: 7,
    },
    {
      name: "Dr. James Anderson",
      appointmentTime: "2:00 PM - 5:00 PM",
      fees: 160,
      category: "Gastroenterologist",
      hospital: "Digestive Health Clinic",
      gender: "Male",
      id: 8,
    },
    {
      name: "Dr. Sophia Lee",
      appointmentTime: "9:00 AM - 12:00 PM",
      fees: 190,
      category: "Ophthalmologist",
      hospital: "Vision Care Institute",
      gender: "Female",
      id: 9,
    },
    {
      name: "Dr. Christopher King",
      appointmentTime: "10:00 AM - 2:00 PM",
      fees: 210,
      category: "Urologist",
      hospital: "Men's Health Clinic",
      gender: "Male",
      id: 10,
    },
    {
      name: "Dr. Rachel Evans",
      appointmentTime: "1:00 PM - 6:00 PM",
      fees: 180,
      category: "Rheumatologist",
      hospital: "Arthritis Relief Center",
      gender: "Female",
      id: 11,
    },
    {
      name: "Dr. William Parker",
      appointmentTime: "8:00 AM - 12:00 PM",
      fees: 270,
      category: "Pulmonologist",
      hospital: "Lung Care Hospital",
      gender: "Male",
      id: 12,
    },
  ];
  export const categories = [
    "Allergist/Immunologist",
    "Anesthesiologist",
    "Cardiologist",
    "Dermatologist",
    "Endocrinologist",
    "Gastroenterologist",
    "Geriatrician",
    "Hematologist",
    "Infectious Disease Specialist",
    "Internal Medicine Specialist",
    "Nephrologist",
    "Neurologist",
    "Obstetrician/Gynecologist (OB/GYN)",
    "Oncologist",
    "Ophthalmologist",
    "Orthopedic Surgeon",
    "Otolaryngologist (ENT Specialist)",
    "Pediatrician",
    "Plastic Surgeon",
    "Psychiatrist",
    "Pulmonologist",
    "Radiologist",
    "Rheumatologist",
    "Sports Medicine Specialist",
    "Surgeon (General)",
    "Urologist",
    "Vascular Surgeon",
  ];